dataset_preprocessing:
  fps: 15
  conf: 0.2
  iou: 0.5
  imgsz: 1280
  maxdet: 12
  # Skip 10% start and end of video
  valid_ratio_start: 0.1
  valid_ratio_end: 0.9
  # ROI crop
  crop_l: 0.25
  crop_r: 0.75
  crop_t: 0.2
  crop_b: 0.6
  presence_in_roi_min: 0.5
  # Motion scoring (To find the player)
  kpt_thr: 0.25
  ema_alpha: 0.6
  idle_active_thr: 0.06
  idle_mean_speed_thr: 0.004
  # Windowing
  win_len: None
  win_stride: None

  save_overlay: False
  max_nan_frame_ratio: 0.5


prepare_base_model:
  model_name: gru
  gru:
    model_name: gru
    num_classes: 18
    hidden: 64
    layers: 1
    dropout: 0.5
    num_joints: 17
    channel: 3
    bidirectional: True

training:
  epochs: 40
  batch_size: 16
  device: cuda
  lr: 0.001
  step_size: 10
  gamma: 0.5
  use_amp: True
