artifacts_root: artifacts

data_ingestion:
  root_dir: data/
  data_url: shenhuichang/badminton-storke-video
  target_path: data/Badminton_Strorke_Video/
  manifest_path: data/Badminton_Strorke_Video/manifest.json

dataset_preprocessing:
  root_dir: artifacts/data_ingestion
  model_name: yolo11n-pose.pt
  manifest_path: data/Badminton_Strorke_Video/manifest.json
  overlay_subdir: overlay_subdir

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  updated_base_model_path: artifacts/prepare_base_model/base_model.pkl

training:
  root_dir: artifacts/training
  base_model_path: artifacts/prepare_base_model/updated_model.pkl
  trained_model_path: artifacts/training/trained_model.pkl
  training_data: artifacts/data_ingestion
  checkpoint_dir: artifacts/training/checkpoints/


